name: Deploy to Webserver

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '21.7.3'

    - name: Change folder
      run: cd punchy-frontend

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: copy file via ssh password
      uses: appleboy/scp-action@v0.1.3
      with:
        host: jorendhaen.be
        username: jorendha
        port: 22
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        overwrite: true
        source: ./dist/*
        target: /home/jorendha/public_html/punchy-frontend
        strip_components: 1



