name: Deploy to Webserver

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.7.3'

      - name: Install dependencies
        run: |
          cd punchy-frontend
          npm install

      - name: Build the project
        run: |
          cd punchy-frontend
          npm run build

      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.3
        with:
          host: jorendhaen.be
          username: jorendha
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          overwrite: true
          source: ./punchy-frontend/dist/*
          target: /home/jorendha/public_html/punchy_frontend
          strip_components: 2

      - name: copy laravel to server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: jorendhaen.be
          username: jorendha
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          overwrite: true
          source: ./punchy-backend/*
          target: /home/jorendha/public_html/punchy_backend
          strip_components: 1
